### ISSUE TITLE
Fix add_step_currents in pointnet/pointsimulator.py

### ISSUE THREAD

**Issue by pgleeson** [AllenInstitute/bmtk#108]
As mentioned here: https://github.com/AllenInstitute/bmtk/pull/107#issuecomment-562159858 there is still an issue with pointsimulator.py with the new code for adding currents. Example error (running https://github.com/AllenInstitute/bmtk/blob/develop/docs/examples/point_iclamp/run_pointnet.py):

```
2019-12-12 16:20:21,171 [INFO] Building recurrent connections
Traceback (most recent call last):
  File "run_pointnet.py", line 14, in <module>
    main('config.json')
  File "run_pointnet.py", line 9, in main
    sim = pointnet.PointSimulator.from_config(configure, network)
  File "/home/padraig/git/bmtk_ai/bmtk/simulator/pointnet/pointsimulator.py", line 266, in from_config
    network.add_step_currents(amp_times, amp_values, node_set, sim_input.name)
  File "/home/padraig/git/bmtk_ai/bmtk/simulator/pointnet/pointsimulator.py", line 153, in add_step_currents
    nest_ids = [self.net._gid2nestid[gid] for gid in node_set.gids()]

```

**Comment by kaeldai** [comment]
Thanks for catching this. I've gone a head and merged in a fix.
