### ISSUE TITLE
Output full vectors of dynamical variables

### ISSUE THREAD

**Issue by crohlicek** [AllenInstitute/bmtk#143]
I'm running the bmtk [chapter 4 tutorial](https://github.com/AllenInstitute/bmtk/blob/b40ff493b493422d350fd9775405af618a69900f/docs/tutorial/04_multi_pop.ipynb) and using a data reporting method from the [bmtk-howto](https://github.com/tjbanks/bmtk-howto/blob/master/pdfs/10-Simple_Data_Manipulation.pdf) from @tjbanks. However, what I need is an output of all the dynamic variables at each time step. I don't see how to get access to more than just a few variables or spike times. Is there a way to get a complete dump of the ODE output?

For reference, here is my configuration file:
```
{
  "target_simulator": "NEURON",
  "run": {
    "tstop": 3000.0,
    "dt": 0.1,
    "dL": 20.0,
    "spike_threshold": -15.0,
    "nsteps_block": 5000
  },
  "conditions": {
    "celsius": 34.0,
    "v_init": -80.0
  },
  "inputs": {
    "LGN_spikes": {
      "input_type": "spikes",
      "module": "nwb",
      "input_file": "./lgn_spikes.nwb",
      "node_set": "LGN",
      "trial": "trial_0"
    }
  },
  "output": {
    "log_file": "log.txt",
    "output_dir": "./output",
    "spikes_file": "spikes.h5",
    "spikes_file_csv": "spikes.csv",
    "overwrite_output_dir": true,
    "cell_vars_dir": "./output/cellvars"
  },
  "reports": {
    "membrane_report": {
      "cells": [
        10,80
      ],
      "sections": "soma",
      "module": "membrane_report",
      "variable_name": [
        "v",
        "cai"
      ]
    },
    "ecp": {
      "cells": [10,80],
      "variable_name": "v",
      "module": "extracellular",
      "electrode_positions": "../components/recXelectrodes/linear_electrode.csv",
      "file_name": "ecp.h5",
      "contributions_dir": "ecp_contributions"
    }
  },
  "recXelectrode": {
    "positions": "$COMPONENT_DIR/recXelectrodes/linear_electrode.csv"
    },
  "network": "./circuit_config.json",
  "config_path": "/Users/chris/Documents/Brown/Research/v1corticalcol/sim_ch04/simulation_config.json",
  "config_dir": "/Users/chris/Documents/Brown/Research/v1corticalcol/sim_ch04",
  "components": {
    "morphologies_dir": "./biophys_components/morphologies",
    "synaptic_models_dir": "./biophys_components/synaptic_models",
    "mechanisms_dir": "./biophys_components/mechanisms",
    "biophysical_neuron_models_dir": "./biophys_components/biophysical_neuron_templates",
    "point_neuron_models_dir": "./biophys_components/point_neuron_templates"
  },
  "networks": {
    "nodes": [
      {
        "node_types_file": "./network/LGN_node_types.csv",
        "nodes_file": "./network/LGN_nodes.h5"
      },
      {
        "node_types_file": "./network/V1_node_types.csv",
        "nodes_file": "./network/V1_nodes.h5"
      }
    ],
    "edges": [
      {
        "edge_types_file": "./network/V1_V1_edge_types.csv",
        "edges_file": "./network/V1_V1_edges.h5"
      },
      {
        "edge_types_file": "./network/LGN_V1_edge_types.csv",
        "edges_file": "./network/LGN_V1_edges.h5"
      }
    ]
  }
}
```

**Comment by kaeldai** [comment]
@crohlicek I created a branch + bionet example that should record all the mechanism states and parameters from the soma of the cells. You'll need to pull the feature/record_mechanisms branch; if you running from the source code:
`$ git fetch && get checkout feature/record_mechanisms`

or using pip
`$ pip install --upgrade git+https://github.com/AllenInstitute/bmtk@feature/record_mechanisms`

Then try running the example simulation under [docs/examples/bio_record_mechanisms/](https://github.com/AllenInstitute/bmtk/tree/feature/record_mechanisms/docs/examples/bio_record_mechanisms). If everything runs correctly then in the output/ folder you should see a bunch of csv files titled cell<N>.<mechanism_name>.csv; where <N> is the cell node_id and <mechanism_name> is for one of the [compiled mechanism mod files found here](https://github.com/AllenInstitute/bmtk/tree/feature/record_mechanisms/docs/examples/biophys_components/mechanisms/modfiles). Each column in the csv will have the trace of a state/parameter variable throughout the simulation and can be read using pandas `pd.read_csv('output/cell0.Ih.csv', sep=' ', index=False)`.

If you're able to get it working you can copy the "record_mechanisms" section of config.json to your own simulation config. Let me know if you run into any issues.

**Comment by crohlicek** [comment]
@kaeldai Thank you so much for making this branch, but I have a couple of questions. First, about running the example simulation, I got the following error when I pip installed the branch and downloaded all the files from the rubdirectory (this followed a call to `python run_bionet.py config.json`):

```
2020-09-19 11:23:44,668 [INFO] Created log file
NEURON mechanisms not found in /Users/chris/Documents/Brown/Research/allen_bmtk_record_test/bio_record_mechanisms/../biophys_components/mechanisms.
2020-09-19 11:23:44,752 [ERROR] Could not find node dynamics_params file /Users/chris/Documents/Brown/Research/allen_bmtk_record_test/bio_record_mechanisms/../biophys_components/biophysical_neuron_templates/472363762_fit.json.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/core/sonata_reader/node_adaptor.py", line 157, in preprocess_node_types
    params_val = json.load(open(params_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chris/Documents/Brown/Research/allen_bmtk_record_test/bio_record_mechanisms/../biophys_components/biophysical_neuron_templates/472363762_fit.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_bionet.py", line 18, in <module>
    run(sys.argv[-1])
  File "run_bionet.py", line 10, in run
    graph = bionet.BioNetwork.from_config(conf)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/core/simulator_network.py", line 246, in from_config
    network.add_nodes(node_pop)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/bionet/bionetwork.py", line 115, in add_nodes
    super(BioNetwork, self).add_nodes(node_population)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/core/simulator_network.py", line 91, in add_nodes
    node_population.initialize(self)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/core/sonata_reader/network_reader.py", line 61, in initialize
    self._adaptor.preprocess_node_types(network, self._node_pop)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/core/sonata_reader/node_adaptor.py", line 161, in preprocess_node_types
    network.io.log_exception('Could not find node dynamics_params file {}.'.format(params_path))
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/core/io_tools.py", line 109, in log_exception
    raise Exception(message)
Exception: Could not find node dynamics_params file /Users/chris/Documents/Brown/Research/allen_bmtk_record_test/bio_record_mechanisms/../biophys_components/biophysical_neuron_templates/472363762_fit.json.
```

Does the above look like an error with how I'm running the example simulation? I tried running it with exactly the contents of the subdirectory you attached but the error looks as though I need to include some other files. 

Separately, I tried copying the "record_mechanisms" into the configuration file of my original simulation (making the right substitutions for the way that model is defined) and got this error: 
```
Traceback (most recent call last):
  File "run_bionet.py", line 21, in <module>
    run(sys.argv[-1])
  File "run_bionet.py", line 14, in run
    sim = bionet.BioSimulator.from_config(conf, network=graph)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/bionet/biosimulator.py", line 500, in from_config
    mod = mods.SpikesMod(**report.params)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/site-packages/bmtk/simulator/bionet/modules/record_spikes.py", line 61, in __init__
    cache_name = os.path.basename(self._h5_fname or self._csv_fname or self._nwb_fname)
  File "/opt/anaconda3/envs/sim_env/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Let me know if these errors point to any simple fix that I'm missing -- thanks again!

**Comment by kaeldai** [comment]
Hi @crohlicek - it looks like you're missing the [biophys_components/ directory](https://github.com/AllenInstitute/bmtk/tree/develop/docs/examples/biophys_components). You'll need to download all the subdirectories otherwise bmtk/NEURON won't be able to find the cell/synapse/mechanism files. If you have downloaded it but it's in a different location on your computer, you can change the config.json file's `$COMPONENT_DIR` value in the "manifest" section. 

You'll also need to (re)-compile the mechanism mod files using NEURON (in the tutorial it's done automatically).
```bash
$ cd biophys_components/mechanisms
$ nrnivmodl modfiles/
```

Hopefully after that it should be ready to run.

**Comment by crohlicek** [comment]
Hi @kaeldai, thanks again for all of this great help -- I took a winding research detour but am back to sorting out a way of getting the full bmtk ODE output and have another question. I've just gone back through your instructions above and tried again to run everything, but I'm running into issues with the config file in [this directory](https://github.com/AllenInstitute/bmtk/tree/feature/record_mechanisms/docs/examples/bio_record_mechanisms) not being able to find the spike inputs in [this directory](https://github.com/AllenInstitute/bmtk/tree/develop/docs/examples/biophys_components). I'm trying to chase down the paths given in the config file but I'm actually finding that I can't see any spike .h5 files in the biophys_components directory. Are the spike inputs that the config file tries to link to (first the lgn spikes and then the tw spikes) located somewhere else where I might be able to find them or is there another way to generate them?
