### ISSUE TITLE
when simulate responses of network .

### ISSUE THREAD

**Issue by keloli** [AllenInstitute/bmtk#194]
Hi, I'm trying to analysis the response of network to arbitrary vision stimuli.

I refer the code in `~/bmtk/docs/examples/filter_movie` and the documents in `https://alleninstitute.github.io/bmtk/filternet.html?highlight=inputs%20section`. 

However, when i run my code to simulate various `inputs`, e.g. full_field_flash, movie_input, excuting `python run_filternet.py configFilternet_full_field_flash.json`, the program raise:
```
2022-01-25 10:20:16,078 [INFO] Building cells.
2022-01-25 10:20:17,057 [INFO] Evaluating rates.
Traceback (most recent call last):  
File "/home/myid/dataset/V1 Network Models from the Allen Institute/LZL_experiments/vision_stimu/filter_movie/run_filternet.py", line 18, in <module>    run(sys.argv[-1])  
File "/home/myid/dataset/V1 Network Models from the Allen Institute/LZL_experiments/vision_stimu/filter_movie/run_filternet.py", line 13, in run    sim.run()  
File "/home/myid/miniconda3/envs/mouse/lib/python3.9/site-packages/bmtk/simulator/filternet/filtersimulator.py", line 109, in run    ts, f_rates = cell.lgn_cell_obj.evaluate(movie, **options)  
File "/home/myid/miniconda3/envs/mouse/lib/python3.9/site-packages/bmtk/simulator/filternet/lgnmodel/lnunit.py", line 13, in evaluate    return self.get_cursor(movie, separable=kwargs.pop('separable', False)).evaluate(**kwargs)  
File "/home/myid/miniconda3/envs/mouse/lib/python3.9/site-packages/bmtk/simulator/filternet/lgnmodel/cursor.py", line 43, in evaluate    y_vals = np.array([self(t) for t in t_range])  
File "/home/myid/miniconda3/envs/mouse/lib/python3.9/site-packages/bmtk/simulator/filternet/lgnmodel/cursor.py", line 43, in <listcomp>    y_vals = np.array([self(t) for t in t_range])  
File "/home/myid/miniconda3/envs/mouse/lib/python3.9/site-packages/bmtk/simulator/filternet/lgnmodel/cursor.py", line 117, in __call__    return self.lnunit.transfer_function(super(LNUnitCursor, self).__call__(t))  
File "/home/myid/miniconda3/envs/mouse/lib/python3.9/site-packages/bmtk/simulator/filternet/lgnmodel/transferfunction.py", line 16, in __call__    return self.closure(s)
  File "<lambdifygenerated-3>", line 2, in _lambdifygenerated
TypeError: <lambda>() takes 1 positional argument but 2 were given
```

My development environment is based on conda. The version of main softwares are: **python=3.9.7, bmtk==0.0.9, neuron==8.0.0, sympy==1.9**.

I am not sure this error is caused by the mismatched software version(maybe i should change python=3.9.7 to python=3.6.10?), or the wrong setting of config.json file, or other reasons.

**Could you give me some suggestions on testing demos, or completed ,or others. Thanks so much!!!**

---------------------------------------------------------
---------------------------------------------------------
Here are some additional information:
The biophysical V1 network model run successfully after executing "mpirun -np 50 nrniv -mpi -python run_bionet.py config.json".
The log.txt is as follows: 
```
2022-01-17 11:24:14,865 [INFO] Created log file
2022-01-17 11:24:14,866 [INFO] Running NEURON with mpi (50 cores).
2022-01-17 11:24:20,074 [INFO] Building cells.
2022-01-17 11:29:38,975 [INFO] Building recurrent connections
2022-01-17 11:47:05,097 [INFO] Building virtual cell stimulations for LGN_spikes
2022-01-17 11:47:28,855 [INFO] Building virtual cell stimulations for BKG_spikes
2022-01-17 11:47:29,988 [INFO] Running simulation for 3000.000 ms with the time step 0.025 ms
2022-01-17 11:47:29,988 [INFO] Starting timestep: 0 at t_sim: 0.000 ms
2022-01-17 11:47:29,988 [INFO] Block save every 20000 steps
2022-01-17 13:56:11,540 [INFO]     step:20000 t_sim:500.00 ms
2022-01-17 15:43:12,846 [INFO]     step:40000 t_sim:1000.00 ms
2022-01-17 17:27:35,502 [INFO]     step:60000 t_sim:1500.00 ms
2022-01-17 19:12:41,625 [INFO]     step:80000 t_sim:2000.00 ms
2022-01-17 21:02:07,543 [INFO]     step:100000 t_sim:2500.00 ms
2022-01-17 22:50:00,012 [INFO]     step:120000 t_sim:3000.00 ms
2022-01-17 22:50:06,705 [INFO] Simulation completed in 11.0 hours, 2.0 minutes and 36.72 seconds 
```

My conda environment, running biophysical V1 network model successfully but failing in run_filternet.py, is as follows：
```
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - boost=1.74.0=py39h5472131_4
  - boost-cpp=1.74.0=h359cf19_5
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.24=py39he80948d_1
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - fonttools=4.28.2=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - gsl=2.7=he838d99_0
  - icu=69.1=h9c3ff4c_0
  - ipykernel=6.5.1=py39hef51801_0
  - ipython=7.29.0=py39hb070fc8_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py39hf3d152e_0
  - jpeg=9d=h36c2ea0_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=h48eae69_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_openblas
  - libcbor=0.8.0=h9c3ff4c_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libfido2=1.9.0=ha19adfc_1
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1d223b6_11
  - liblapack=3.9.0=12_linux64_openblas
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h7f98852_1
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=8.0.1=hc9558a2_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.0=py39h2fa2bec_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.2=py39hc649577_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nest-simulator=2.20.2=py39hadb4b93_2
  - numpy=1.20.3=py39hdbf815f_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openmp=8.0.1=0
  - openmpi=4.1.1=hbfc84c5_0
  - openssh=8.8p1=h4b68de1_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py39hde0f152_1
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py39h37b5a0c_1
  - readline=8.1=h46c0cb4_0
  - scipy=1.7.2=py39hee8e79c_0
  - setuptools=59.2.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_2
  - statsmodels=0.13.1=py39hce5d2b2_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py39h3811e60_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - tzdata=2021e=he74cb21_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - attrs==21.2.0
    - bmtk==0.0.9
    - h5py==3.6.0
    - imageio==2.13.5
    - joblib==1.1.0
    - jsonschema==4.4.0
    - mpmath==1.2.1
    - networkx==2.6.3
    - neuron==8.0.0
    - pynest==nest-2.20.2
    - pyrsistent==0.18.1
    - pywavelets==1.2.0
    - scikit-image==0.19.1
    - scikit-learn==1.0.1
    - sklearn==0.0
    - sympy==1.9
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
    - topology==nest-2.20.2
```

**Comment by kaeldai** [comment]
Hi @keloli. Can you post the contents of the `configFilternet_full_field_flash.json` file, in particularlly the "inputs" section?

**Comment by keloli** [comment]
Hi, @kaeldai , the content of my `configFilternet_full_field_flash.json` is:
```
{
    "manifest": {
        "$BASE_DIR": "${configdir}",
        "$OUTPUT_DIR": "$BASE_DIR/output",
        "$INPUT_DIR": "$BASE_DIR/movie_files",
        "$NETWORK_DIR": "$BASE_DIR/network"
    },

    "run": {
        "tstop": 2050.0,
        "dt": 0.1,
        "overwrite_output_dir": true
    },

    "target_simulator": "NEURON",

    "conditions": {
        "jitter_lower": 1.0,
        "jitter_upper": 1.0
    },

"inputs": {
        "full_field_flash": {
            "input_type": "movie",
            "module": "full_field_flash",            
            "row_size": 120,
            "col_size": 240,
            "t_on": 1000.0,
            "t_off": 2000.0,
            "max_intensity": 20.0
        }
    },

    "output": {
        "log_file": "$OUTPUT_DIR/log.txt",
        "output_dir": "$OUTPUT_DIR",
        "rates_csv": "$OUTPUT_DIR/rates.csv",
        "spikes_csv": "$OUTPUT_DIR/spikes.csv",
        "spikes_h5": "$OUTPUT_DIR/spikes.h5",
        "overwrite_output_dir": true
    },

    "components": {
        "filter_models_dir": "$BASE_DIR"
    },

    "networks": {
        "nodes": [
            {
                "nodes_file": "$NETWORK_DIR/lgn_nodes.h5",
                "node_types_file": "$NETWORK_DIR/lgn_node_types.csv"
            }
        ]
    }
}

```

I copy the related sON*.json, sOFF*.json, tON*.json and tOFF*.json to the same directory with `configFilternet_full_field_flash.json`. 

The configuration of "inputs" section is copy from https://alleninstitute.github.io/bmtk/filternet.html # Full Field Flash. 

My python version is 3.9.7.  The "__call__"function in "/bmtk/simulator/filternet/lgnmodel/cursor.py", line 117, in __call__    return self.lnunit.transfer_function(super(LNUnitCursor, self).__call__(t)) could run successfully by python=3.9.7?

Thanks for your reply and hope you can give me some suggestions!

**Comment by kaeldai** [comment]
Hi @keloli

It looks like the issue was with the method signature for the Heaviside function in sympy 1.9. The easiest way to fix this is to downgrade sympy (I've tested using sympy 1.5.1, 1.6, and 1.8); `$ pip install sympy==1.8`. 

If you want to keep the sympy version the way it is I've also made some necessary changes to bmtk that should also fix it. You'll need to pull the latest version of bmtk from the develop branch and update bmtk in conda:
```bash
$ git pull origin develop
$ python setup.py install
```

Thanks,
Kael

**Comment by keloli** [comment]
Hi, @kaeldai 

Thanks so much! Now i can get 'spikes.csv' and other results after "graiting“ inputs. 

However, when i refer the code:
```
from bmtk.analyzer.visualization.spikes import plot_raster

plot_raster('sim_ch07/output/spikes.h5', nodes_file='sim_ch07/network/lgn_nodes.h5',
            node_types_file='sim_ch07/network/lgn_node_types.csv', group_by='model_template')
```
in `https://alleninstitute.github.io/bmtk/tutorial_filter_models.html`  to visulize the results, the program raise: `ModuleNotFoundError: No module named 'bmtk.analyzer.visualization`.

I try to read the soure code and i find that in `bmtk v1.0.0`, `plot_raster()` may be reorganized in `bmtk.analyzer.spike_train.plot_raster()`. I read the function's new definition: 
```
def plot_raster(config_file=None, population=None, with_histogram=True, times=None, title=None, show=True,
                group_by=None, group_excludes=None,
                spikes_file=None, nodes_file=None, node_types_file=None)
````
I appreciate you proving more optional params for plotting raster figures. However, the new `plot_raster()` seems do not provide param 'save_as', which may help user to save the displayed plot/figure.

Could you give some suggestions to save the raster plot.

Thanks!

**Comment by kaeldai** [comment]
Hi @keloli - you are right that the new plotting function is missing a *save_as* option, and I will add it to future versions of bmtk. 

But in the mean time, the ```plot_raster()``` function should return a matplotlib Figure object which you can use to save the raster:

```python
from bmtk.analyzer.spike_trains import plot_raster

fig = plot_raster(spikes_file='output/spikes.h5', show=False) 
fig.savefig('movie_raster.png')
```
