### ISSUE TITLE
Possible issues with latest versions of H5py and Pandas

### ISSUE THREAD

**Issue by tjbanks** [AllenInstitute/bmtk#66]
I kept running into the two following errors until I downgraded h5py from ```2.8.0``` to ```2.7.0``` and pandas from  ```0.24.1``` to  ```0.20.3``` 

```
pip install h5py==2.7.0 pandas==0.23.0
```

```
(base) C:\Users\Tyler\Desktop\git_stage\project>python run_bionet.py
2019-03-12 22:19:58,928 [INFO] Created log file
2019-03-12 22:19:59,038 [INFO] Building cells.
2019-03-12 22:19:59,773 [INFO] Building recurrent connections
2019-03-12 22:20:38,338 [INFO] Building virtual cell stimulations for exc_spikes
Traceback (most recent call last):
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.7.egg\bmtk\utils\sonata\population.py", line 586, in _get_index
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_bionet.py", line 34, in <module>
    run('simulation_config.json')
  File "run_bionet.py", line 22, in run
    sim = bionet.BioSimulator.from_config(conf, network=graph)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.7.egg\bmtk\simulator\bionet\biosimulator.py", line 291, in from_config
    network.add_spike_trains(spikes, node_set)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.7.egg\bmtk\simulator\bionet\bionetwork.py", line 260, in add_spike_trains
    for edge in edge_pop.get_target(trg_nid):
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.7.egg\bmtk\simulator\core\sonata_reader\network_reader.py", line 174, in get_target
    for edge in self._edge_pop.get_target(node_id):
RuntimeError: generator raised StopIteration
```
Pandas error:
```
(base) C:\Users\Tyler\Desktop\git_stage\project>python run_bionet.py
C:\Users\Tyler\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-03-12 23:17:37,341 [INFO] Created log file
Traceback (most recent call last):
  File "run_bionet.py", line 34, in <module>
    run('simulation_config.json')
  File "run_bionet.py", line 21, in run
    graph = bionet.BioNetwork.from_config(conf)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.6.egg\bmtk\simulator\core\simulator_network.py", line 169, in from_config
    network.add_nodes(node_pop)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.6.egg\bmtk\simulator\core\simulator_network.py", line 87, in add_nodes
    node_population.initialize(self)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.6.egg\bmtk\simulator\core\sonata_reader\network_reader.py", line 44, in initialize
    model_types.update(set(np.unique(grp.get_values(self._adaptor.COL_MODEL_TYPE))))
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.6.egg\bmtk\utils\sonata\group.py", line 182, in get_values
    self.build_indicies()
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.6.egg\bmtk\utils\sonata\group.py", line 178, in build_indicies
    self._parent_indicies = self._parent.group_indicies(self.group_id, build_cache=True)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\bmtk-0.0.7-py3.6.egg\bmtk\utils\sonata\population.py", line 125, in group_indicies
    tmp_index['grp_id'] = pd.Series(self._group_id_ds, dtype=self._group_id_ds.dtype)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\pandas\core\series.py", line 262, in __init__
    raise_cast_failure=True)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 625, in sanitize_array
    subarr = _try_cast(data, False, dtype, copy, raise_cast_failure)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 695, in _try_cast
    subarr = maybe_cast_to_integer_array(arr, dtype)
  File "C:\Users\Tyler\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1307, in maybe_cast_to_integer_array
    casted = arr.astype(dtype, copy=copy)
TypeError: astype() got an unexpected keyword argument 'copy'
```

**Comment by trashpirate** [comment]
I had the same issue, and downgrading to the versions mentioned above worked.

**Comment by kaeldai** [comment]
The Pandas 'copy' issue was with trying to implicitly convert a dataframe to a numpy array, and has been fixed in the code. 

I have tested the the iteration issue with python 3.6 and 3.7, h5py 0.24.1 and 3.2.1, pandas 0.24.1 and 1.2.3. I believe the issues have been fixed in another push.
