### ISSUE TITLE
plot_report single plot issue

### ISSUE THREAD

**Issue by tjbanks** [AllenInstitute/bmtk#83]
Minor and may not be worth the time to fix. Feel free to close.
When plotting a single variable for a gid other than 0, using ```bmtk/analyzer/cell_vars.plot_report()``` I get the following error.

```
Traceback (most recent call last):
  File "/home/tbg28/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tbg28/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tbg28/git_stage/bmtools/bmtools/plot.py", line 621, in <module>
    handling_func(**v)
  File "/home/tbg28/git_stage/bmtools/bmtools/plot.py", line 375, in plot_report_default
    plot_report(config_file=config, report_file=report_file, report_name=report_name, variables=variables, gids=gids);
  File "/home/tbg28/git_stage/bmtk/bmtk/analyzer/cell_vars.py", line 71, in plot_report
    plt.plot(time_steps, var_report.data(gid=0, var_name=variables[0]), label='gid {}'.format(gid))
  File "/home/tbg28/git_stage/bmtk/bmtk/utils/cell_vars/var_reader.py", line 121, in data
    gid_slice = self._gid2data_table[gid][0]
KeyError: 0

```

It appears there's a hard-coded ```0``` that should be replaced with ```gid``` here:
https://github.com/AllenInstitute/bmtk/blob/develop/bmtk/analyzer/cell_vars.py#L71

```
        for gid in gids:
            plt.plot(time_steps, var_report.data(gid=0, var_name=variables[0]), label='gid {}'.format(gid))
```

**Comment by kaeldai** [comment]
The code has changed and the hard-coded plot function has been replaced. I can still reproduce the KeyError exception whenever it tries to plot an invalid node id. I've updated it so there is a better error message.
